# Generated by Django 5.1.1 on 2024-09-24 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание услуги'),
        ),
        migrations.CreateModel(
            name='ServicesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Foto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.service')),
            ],
        ),
    ]
